<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Objectives" data-toc-modified-id="Objectives-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Objectives</a></span></li><li><span><a href="#Inheritance" data-toc-modified-id="Inheritance-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Inheritance</a></span><ul class="toc-item"><li><span><a href="#Motivation:-So-What's-the-Benefit?" data-toc-modified-id="Motivation:-So-What's-the-Benefit?-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Motivation: So What's the Benefit?</a></span></li><li><span><a href="#Inheritance-in-Data-Science" data-toc-modified-id="Inheritance-in-Data-Science-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Inheritance in Data Science</a></span></li></ul></li><li><span><a href="#Duck-Typing" data-toc-modified-id="Duck-Typing-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Duck Typing</a></span><ul class="toc-item"><li><span><a href="#Duck-Typing-in-Scikit-Learn" data-toc-modified-id="Duck-Typing-in-Scikit-Learn-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Duck Typing in Scikit-Learn</a></span></li></ul></li><li><span><a href="#Scikit-Learn's-API:-(Estimators,-Transformers,-Predictors)" data-toc-modified-id="Scikit-Learn's-API:-(Estimators,-Transformers,-Predictors)-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Scikit-Learn's API: (Estimators, Transformers, Predictors)</a></span><ul class="toc-item"><li><span><a href="#Estimator" data-toc-modified-id="Estimator-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Estimator</a></span><ul class="toc-item"><li><span><a href="#fit" data-toc-modified-id="fit-4.1.1"><span class="toc-item-num">4.1.1&nbsp;&nbsp;</span><code>fit</code></a></span></li></ul></li><li><span><a href="#Transformer" data-toc-modified-id="Transformer-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Transformer</a></span><ul class="toc-item"><li><span><a href="#transform" data-toc-modified-id="transform-4.2.1"><span class="toc-item-num">4.2.1&nbsp;&nbsp;</span><code>transform</code></a></span></li><li><span><a href="#fit_transform" data-toc-modified-id="fit_transform-4.2.2"><span class="toc-item-num">4.2.2&nbsp;&nbsp;</span><code>fit_transform</code></a></span></li></ul></li><li><span><a href="#Predictor" data-toc-modified-id="Predictor-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Predictor</a></span><ul class="toc-item"><li><span><a href="#predict" data-toc-modified-id="predict-4.3.1"><span class="toc-item-num">4.3.1&nbsp;&nbsp;</span><code>predict</code></a></span></li><li><span><a href="#score" data-toc-modified-id="score-4.3.2"><span class="toc-item-num">4.3.2&nbsp;&nbsp;</span><code>score</code></a></span></li></ul></li><li><span><a href="#Observing-a-Scikit-Learn-Class-Definition-from-Source" data-toc-modified-id="Observing-a-Scikit-Learn-Class-Definition-from-Source-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Observing a Scikit-Learn Class Definition from Source</a></span></li></ul></li><li><span><a href="#Creating-a-Scikit-Learn-Transformer" data-toc-modified-id="Creating-a-Scikit-Learn-Transformer-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Creating a Scikit-Learn Transformer</a></span><ul class="toc-item"><li><span><a href="#Creating-a-New-Transformer" data-toc-modified-id="Creating-a-New-Transformer-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Creating a New Transformer</a></span></li><li><span><a href="#Creating-a-fit-Method" data-toc-modified-id="Creating-a-fit-Method-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Creating a <code>fit</code> Method</a></span></li><li><span><a href="#Creating-transform-Method" data-toc-modified-id="Creating-transform-Method-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Creating <code>transform</code> Method</a></span></li><li><span><a href="#Conclusion" data-toc-modified-id="Conclusion-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>Conclusion</a></span></li></ul></li><li><span><a href="#Exercise:-Create-Your-Own-Transformer" data-toc-modified-id="Exercise:-Create-Your-Own-Transformer-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Exercise: Create Your Own Transformer</a></span><ul class="toc-item"><li><span><a href="#Test-Your-Code!" data-toc-modified-id="Test-Your-Code!-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Test Your Code!</a></span></li></ul></li></ul></div>

In [1]:
import numpy as np
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# Objectives

- Understand the concept of object-oriented inheritance
- Understand the main object types of the Scikit-Learn API
- Extend and create custom Scikit-Learn Estimators

# Inheritance

We've learned a lot already on object-oriented programming and how to create our own classes.

We can also define classes in terms of _other_ classes, in which case the new classes **inherit** the attributes and methods from the classes in terms of which they're defined.

## Motivation: So What's the Benefit? 

_More abstraction is better_

Take a look at this code below. Look at how much we've already done:

In [2]:
# Look at all that code we wrote... do we have to do it all again...?
class Robot():
    purpose = 'To love humans'
    
    # We'd like to start off with some initial attributes
    def __init__(self, first_name='?', last_name=''):
        # Clean the names of extra spaces at beginning & end
        first_name = first_name.strip()
        last_name = last_name.strip()    
        # Setting attributes
        self._first_name = first_name
        self._last_name = last_name
        # Combine first and last names and remove any extra spacing
        self.name = ' '.join([first_name,last_name]).strip()

           
    def change_name(self, new_name):
        self.name = new_name
    
    def speak(self):
        print(f'I am {self.name}!')

Let's say we wanted to make another bot with some extra functionality like keeping track of its battery charge.

Do we have to copy and paste this and then add our new functionality? 

Nope! Since we can abstract away the stuff we already did!

In [3]:
class GarbageBot(Robot): # Specify the base class(es) we inherit from
    '''A robot that takes care of garbage while we're away!'''
    # Added functionality
    battery = 100
    
    def speak(self):
        print(f"I'm {self.name} and have {self.battery}% battery charged")
        self.battery -= 10

In [4]:
new_robot = GarbageBot('Wall-e')
new_robot.speak()

I'm Wall-e and have 100% battery charged


In [5]:
new_robot.speak()

I'm Wall-e and have 90% battery charged


In [6]:
new_robot.battery

80

And I still keep the other functionality from the original class!

In [7]:
new_robot.change_name('E-llaw') # Note we never defined this in GarbageBot!
new_robot.speak()

I'm E-llaw and have 80% battery charged


## Inheritance in Data Science

A lot of motivation in how we write our code can be summed up with, "Never reinvent the wheel". And using **inheritance** can make this really easy.

Later, we'll be taking Scikit-Learn's objects and customizing them to our particular needs. This can be a common practice as we use libraries and tools to write reproducible code.

Inheritance allows us to write some of this code quickly by avoiding a lot of "boilerplate" code (the same code we write over and over just to do a minor change).

# Duck Typing

But we don't need inheritance to do everything. 

A different method of getting functionality using different objects is called **duck typing**. The term comes from the saying: 
> **"If it walks like a duck and it quacks like a duck, then it must be a duck."**

![](images/duck.jpg)
> <a href="https://commons.wikimedia.org/wiki/File:Rubber_Duck_Front_View_in_Fine_Day_20140107.jpg">玄史生</a>, <a href="https://creativecommons.org/licenses/by-sa/3.0">CC BY-SA 3.0</a>, via Wikimedia Commons

When you're using the concept of duck typing, you really don't care about the object _type_ and if it's compatible.

All you _care about are the **methods and properties**_ of the object over the type or even class.

## Duck Typing in Scikit-Learn

Scikit-Learn relies more on duck typing over pure inheritance. In general, if an object has certain methods that `sklearn` expects, than it's mostly compatible!

However, inheritance in Scikit-Learn is typically used to avoid _boilerplate_ code. Usually this involves using [`sklearn.base`](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.base) such as [`sklearn.base.BaseEstimator`](https://scikit-learn.org/stable/modules/generated/sklearn.base.BaseEstimator.html#sklearn.base.BaseEstimator).

# Scikit-Learn's API: (Estimators, Transformers, Predictors)

Scikit-Learn has a great [API](https://scikit-learn.org/stable/developers/develop.html) that has objects that are consistent and easy to make compatible with your own made objects!

Let's go over the API's object that will be most relevant to us in the near future.

## Estimator

> This is an object that can can take in data and _estimate_ (or *learn*) some parameters. 

This means regression and classification models are estimators but so are objects that transform the original dataset ([Transformers](#Transformer)) such as `StandardScaler`.

### `fit`

All estimators estimate/learn by calling the `fit()` method by passing in the dataset. Other parameters can be passed in to "help" the estimator to learn. These are called **hyperparameters**, parameters used to tweak the learning process.

## Transformer

> Some estimators can change the original data to something new, a **transformation**. 

You can think of examples of these **transformers** when you do scaling, data cleaning, or expanding/reducing on a dataset.

### `transform`

Transformers will call the `transform()` method to apply the transformation to a dataset after a `fit()` call.

###  `fit_transform`

Remember that all estimators have a `fit()` method, so a transformer can use the `fit()` method to learn something about the given dataset. After learning with `fit()`, a transformation on the dataset can be made with the `transform()` method. 

An example of this would be a function that performs normalization on the dataset; the `fit()` method would learn the minimum and maximum of the dataset and the `transform()` method will scale the dataset.

When you call `fit` and `transform` with the same dataset, you can simply call the `fit_transform()` method. This essentially has the same results as calling `fit()` and then `transform()` on the dataset but possibly with some optimization and efficiencies baked in.

## Predictor

> We would use the `fit()` method to train our predictor object and then feed in new data to make predictions (based on what it learned in the fitting stage).

We've used **predictors** whenever we've made predictions like with a `LinearRegression` model.

### `predict`

As you probably can guess, the `predict()` method predicts results from a dataset given to it after being trained with a `fit()` method

### `score`

Predictors also have a `score()` method that can be used to evaluate how well the predictor performed on a dataset (such as the test set).

## Observing a Scikit-Learn Class Definition from Source

Let's begin by taking a look at the source code for `sklearn`'s [StandardScaler](https://github.com/scikit-learn/scikit-learn/blob/fd237278e/sklearn/preprocessing/_data.py#L517)

Take a minute to peruse the source code on your own. What do you notice?

# Creating a Scikit-Learn Transformer

> Sometimes we want to create our own Scikit-Learn objects to be used in our code.

Let's try to create a new _transformer_ that will transform the data in the following manner:

- If the value is **positive**, scale the value by the **largest value** in that column
- If the value is **negative**, change it to $0$

## Creating a New Transformer

First, we create our base estimator/transformer through inheritance of [`sklearn.base.BaseEstimator`](https://scikit-learn.org/stable/modules/generated/sklearn.base.BaseEstimator.html#sklearn.base.BaseEstimator):

In [8]:
class SpecialTransformer(BaseEstimator):
    pass

my_transformer = SpecialTransformer()
my_transformer

SpecialTransformer()

This by itself is pretty useless. But we can now add in new `fit()` method which will find the maximum value for each column/feature.

In [ ]:
my_transformer.

## Creating a `fit` Method

In [32]:
class SpecialTransformer(BaseEstimator):
    
    def fit(self, X, y=None): # By convention, we accept a y parameter
        # Get the maximum value for each column/feature
        # Note we use an ending underscore for values "learned" from fit()
        self.max_ = np.max(X, axis=0)
        return self

In [33]:
my_transformer = SpecialTransformer()

In [21]:
## Let's use some test data
# Note each column is a feature, each row a data point
X = np.array([
    [-4, 400, 40],
    [10, -100, 1],
    [6, -800, 700],
    [2, 0, 400],
    [8, 200, 1000]
])

X

array([[  -4,  400,   40],
       [  10, -100,    1],
       [   6, -800,  700],
       [   2,    0,  400],
       [   8,  200, 1000]])

In [22]:
import pandas as pd

In [23]:
list(pd.DataFrame(X).max())

[10, 400, 1000]

In [24]:
list(np.max(pd.DataFrame(X)))

[10, 400, 1000]

In [25]:
list(np.max(X, axis=0))

[10, 400, 1000]

> Quick check: What would be the max values for each column/feature?

In [26]:
my_transformer.max_

AttributeError: 'SpecialTransformer' object has no attribute 'max_'

### Why didn't this work?

In [34]:
# No transformation yet need to fit first, then can get the maximum values
my_transformer.fit(X).max_


array([  10,  400, 1000])

In [35]:
my_transformer.fit(X)

SpecialTransformer()

Great! 

## Creating `transform` Method

Let's now actually implement a way to transform our data:

In [36]:
class SpecialTransformer(BaseEstimator):
    
    def fit(self, X, y=None):
        self.max_ = np.max(X, axis=0) 
        return self
    
    def transform(self, X):
        '''
        Scale the values passed in: 
            - Negatives go to 0
            - Positives scaled by maximum value found in fit()
        '''
        X_copy = np.copy(X)
        # If value is negative turn in into a 0
        X_copy[X_copy < 0] = 0
        # If value is positive, scale based on max value
        return X_copy / self.max_

In [43]:
X

array([[  -4,  400,   40],
       [  10, -100,    1],
       [   6, -800,  700],
       [   2,    0,  400],
       [   8,  200, 1000]])

In [47]:
my_transformer.max_[0]

10

In [45]:
X[0][0]

-4

In [42]:
for value in X:
    print(value)

[ -4 400  40]
[  10 -100    1]
[   6 -800  700]
[  2   0 400]
[   8  200 1000]


In [37]:
# Recall the data
X

array([[  -4,  400,   40],
       [  10, -100,    1],
       [   6, -800,  700],
       [   2,    0,  400],
       [   8,  200, 1000]])

In [38]:
# Create a SpecialTransformer and fit with the data
my_transformer = SpecialTransformer()
my_transformer.fit(X)

SpecialTransformer()

In [39]:
# Transform the data
X_new = my_transformer.transform(X)
X_new

array([[0.   , 1.   , 0.04 ],
       [1.   , 0.   , 0.001],
       [0.6  , 0.   , 0.7  ],
       [0.2  , 0.   , 0.4  ],
       [0.8  , 0.5  , 1.   ]])

## Conclusion

We now created our very own transformer! We could even feed in one data set to _fit_ our object and then a different dataset to _transform_.

We should note that there's still a lot of customization we could have done. 

For example, we didn't consider what happens if the maximum value for a feature was $0$. We really should code how we want that to be handled (but we just ignored it for now).

We also could have gotten the `fit_transform()` method automatically by also inheriting from [`TransformerMixin`](https://scikit-learn.org/stable/modules/generated/sklearn.base.TransformerMixin.html#sklearn.base.TransformerMixin). See the code below:

In [48]:
class SpecialTransformer(BaseEstimator, TransformerMixin):
    
    def fit(self, X, y=None):
        self.max_ = np.max(X,axis=0) 
        return self
    
    def transform(self, X):
        X_copy = np.copy(X)
        X_copy[X_copy < 0] = 0
        return X_copy / self.max_

In [49]:
my_transformer = SpecialTransformer()
# Note we can now do fit_transform()
X_new = my_transformer.fit_transform(X)
X_new

array([[0.   , 1.   , 0.04 ],
       [1.   , 0.   , 0.001],
       [0.6  , 0.   , 0.7  ],
       [0.2  , 0.   , 0.4  ],
       [0.8  , 0.5  , 1.   ]])

# Exercise: Create Your Own Transformer

Your turn! Let's try to recreate the [`StandardScaler`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html) object!

Recall that standard scaling transforms the values in the following way:

$$x_i = \frac{x_i-\bar{x_i}}{\sigma_{x_i}}$$

where the $i$ subscript reminds us that it comes from a single column/feature.

In [54]:
## YOUR CODE HERE!
class MyStandardScaler(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        self.mean_ = np.mean(X, axis=0)
        self.scale_ = np.std(X, axis=0)
        return self
    
    def transform(self, X, y=None):
        X_copy = np.copy(X)
        return (X_copy - self.mean_) / self.scale_

<details>
    <summary>Answer</summary>
        <code>class MyStandardScaler:
    def fit(self, arr):
        self.mean_ = np.mean(arr, axis=0)
        self.scale_ = np.std(arr, axis=0)
    def transform(self, arr):
        return (arr - self.mean_) / self.scale_</code>
</details>

## Test Your Code!

Once you have it, you can test it against the data below and Scikit-Learn's `StandardScaler`

In [51]:
# Your test data
X = np.array([
    [-4, 400, 40],
    [10, -100, 1],
    [6, -800, 700],
    [2, 0, 400],
    [8, 200, 1000]
])
X

array([[  -4,  400,   40],
       [  10, -100,    1],
       [   6, -800,  700],
       [   2,    0,  400],
       [   8,  200, 1000]])

In [52]:
# Test against StandardScaler
sklearn_scaler = StandardScaler()
X_sklearn_scaled = sklearn_scaler.fit_transform(X)
X_sklearn_scaled

array([[-1.69222822,  1.12766778, -1.01262497],
       [ 1.12815215, -0.09805807, -1.114357  ],
       [ 0.32232919, -1.81407425,  0.70899399],
       [-0.48349378,  0.1470871 , -0.07356008],
       [ 0.72524067,  0.63737744,  1.49154806]])

In [55]:
myss = MyStandardScaler()
myss.fit_transform(X)

array([[-1.69222822,  1.12766778, -1.01262497],
       [ 1.12815215, -0.09805807, -1.114357  ],
       [ 0.32232919, -1.81407425,  0.70899399],
       [-0.48349378,  0.1470871 , -0.07356008],
       [ 0.72524067,  0.63737744,  1.49154806]])

In [56]:
# Catches errors
try:
    # Your implementation
    my_scaler = MyStandardScaler()
    my_scaler.fit(X)
    X_my_scaled = my_scaler.transform(X)
    
    # Check against StandardScaler
    print('StandardScaler and MyStandardScaler same?')
    print(X_sklearn_scaled == X_my_scaled)
except:
    print('Check your fit() and transform() methods!')

StandardScaler and MyStandardScaler same?
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Objectives Recap

- Understand the concept of object-oriented inheritance
- Understand the main object types of the Scikit-Learn API
- Extend and create custom Scikit-Learn Estimators

In [70]:
animal1 = {'type': 'Tiger', 'height': 50, 'weight': 80, 'name': 'Billy Bob', 'diet': 'Low-Fat'}

In [71]:
animal1['name']

'Billy Bob'

In [72]:
animal1

{'type': 'Tiger',
 'height': 50,
 'weight': 80,
 'name': 'Billy Bob',
 'diet': 'Low-Fat'}

In [77]:
class zoo_animal:
    def __init__(self, data):
        self.name = data['name']
        self._type = data['type']

In [74]:
tiger = zoo_animal(animal1)

In [75]:
tiger.name

'Billy Bob'

In [76]:
tiger.type

'Tiger'

In [81]:
class tiger_animals(zoo_animal):
    color = 'White/Orange'

In [82]:
tiger2 = tiger_animals(animal1)

In [83]:
tiger2.color

'White/Orange'

In [89]:
class Rando(Robot):
    pass